const LS_MEMBERS='memberhub_static_members_v2';
const LS_SETTINGS='memberhub_static_settings_v2';
const defaultSettings={companyName:'我的機構',password:'',memberPrefix:'MEM',startNumber:1,includeYear:true,includeMonth:false,currentSequence:1};
let state={page:'home',members:load(LS_MEMBERS,[]),settings:load(LS_SETTINGS,defaultSettings),form:null,search:'',month:monthKey(new Date()),toast:'',viewMember:null};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function pad(n,l=4){return String(n).padStart(l,'0')}
function monthKey(d){const x=new Date(d);return `${x.getFullYear()}-${pad(x.getMonth()+1,2)}`}
function today(){return new Date().toLocaleDateString('zh-HK',{year:'numeric',month:'2-digit',day:'2-digit'})}
function age(dob){if(!dob)return'';const d=new Date(dob),n=new Date();let a=n.getFullYear()-d.getFullYear();const m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))a--;return a>=0?a:''}
function nextNo(settings=state.settings){const d=new Date();let parts=[];if(settings.includeYear)parts.push(d.getFullYear());if(settings.includeMonth)parts.push(pad(d.getMonth()+1,2));parts.push(settings.memberPrefix||'MEM');parts.push(pad(settings.currentSequence||settings.startNumber||1));return parts.join('-')}
function newForm(){return{memberNumber:nextNo(),name:'',gender:'',dateOfBirth:'',age:'',hkid:'',phone:'',email:'',address:'',emergencyContactName:'',emergencyContactPhone:'',healthDeclaration:false,remarks:''}}
function setPage(p){if(p==='settings'&&state.settings.password){const x=prompt('請輸入系統密碼');if(x!==state.settings.password){toast('密碼不正確');return}}state.page=p;state.viewMember=null;if(p==='register'&&!state.form)state.form=newForm();render()}
function requirePassword(actionLabel='操作'){
  if(!state.settings.password){
    const create=confirm('尚未設定系統密碼。為保障會員私隱，請先到設定頁建立密碼。是否前往設定？');
    if(create) setPage('settings');
    return false;
  }
  const x=prompt(`請輸入系統密碼以${actionLabel}`);
  if(x!==state.settings.password){toast('密碼不正確');return false}
  return true
}
function viewMember(id){if(!requirePassword('查看會員詳情'))return;state.viewMember=state.members.find(m=>m.id===id)||null;render()}
function closeView(){state.viewMember=null;render()}
function toast(msg){state.toast=msg;render();setTimeout(()=>{state.toast='';render()},1800)}
function updateForm(k,v){
  state.form={...state.form,[k]:v};
  if(k==='dateOfBirth'){
    state.form.age=age(v);
    const ageInput=document.querySelector('[data-key=\"age\"]');
    if(ageInput) ageInput.value=state.form.age;
  }
}
function validateForm(){const f=state.form;const req=['name','gender','dateOfBirth','hkid','phone'];for(const r of req){if(!f[r])return `請填寫：${labelMap[r]}`;}if(f.email&&!/^\S+@\S+\.\S+$/.test(f.email))return '電郵格式不正確';if(!/^[0-9+\-\s]{8,}$/.test(f.phone))return '電話格式不正確';if(!f.healthDeclaration)return '請確認沒有重大疾病聲明';if(state.members.some(m=>m.memberNumber===f.memberNumber))return '會員編號重複，請到設定調整流水號';return ''}
const labelMap={name:'姓名',gender:'性別',dateOfBirth:'出生年月日',hkid:'身份證號碼',phone:'電話號碼'};
function submitMember(){const err=validateForm();if(err){alert(err);return}const now=new Date().toISOString();const member={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...state.form,createdAt:now,updatedAt:now};state.members=[member,...state.members];state.settings.currentSequence=(state.settings.currentSequence||state.settings.startNumber||1)+1;save(LS_MEMBERS,state.members);save(LS_SETTINGS,state.settings);state.form=null;state.page='members';toast('會員已成功儲存');render()}
function delMember(id){if(!requirePassword('刪除會員'))return;if(!confirm('確定刪除此會員？此動作不能復原。'))return;state.members=state.members.filter(m=>m.id!==id);save(LS_MEMBERS,state.members);state.viewMember=null;toast('已刪除會員');render()}
function exportWord(member){const rows=memberRows(member).map(([a,b])=>`<tr><td><b>${a}</b></td><td>${escapeHtml(b)}</td></tr>`).join('');const html=`<html><head><meta charset="UTF-8"><title>會員登記表</title></head><body><h2>${state.settings.companyName} - 會員登記表</h2><table border="1" cellspacing="0" cellpadding="8">${rows}</table></body></html>`;downloadBlob(html,`會員登記表_${member.memberNumber}_${member.name}_${today()}.doc`,'application/msword')}
function exportPDF(member){const print=document.getElementById('printArea');print.innerHTML=printDoc(member);window.print()}
function downloadBlob(content,name,type){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]))}
function memberRows(m){return[['公司名稱',state.settings.companyName],['會員編號',m.memberNumber],['姓名',m.name],['性別',m.gender],['出生日期',m.dateOfBirth],['年齡',m.age],['身份證號碼',m.hkid],['電話',m.phone],['電郵',m.email],['住址',m.address],['緊急聯絡人',m.emergencyContactName],['緊急聯絡人電話',m.emergencyContactPhone],['沒有重大疾病聲明',m.healthDeclaration?'已確認':'未確認'],['備註',m.remarks],['登記日期',new Date(m.createdAt).toLocaleString('zh-HK')]]}
function printDoc(m){return `<div class="printDoc"><h2>${escapeHtml(state.settings.companyName)}</h2><h2>會員登記表</h2><table class="printTable">${memberRows(m).map(([a,b])=>`<tr><td><b>${escapeHtml(a)}</b></td><td>${escapeHtml(b)}</td></tr>`).join('')}</table><p style="margin-top:28px">會員簽署：__________________________</p></div>`}
function uniqueMonths(){const set=new Set(state.members.map(m=>monthKey(m.createdAt)));set.add(monthKey(new Date()));return [...set].sort().reverse()}
function filteredMembers(){const q=state.search.trim().toLowerCase();return state.members.filter(m=>monthKey(m.createdAt)===state.month).filter(m=>!q||[m.name,m.memberNumber,m.phone,m.hkid].some(x=>String(x||'').toLowerCase().includes(q)))}
function home(){const nowM=monthKey(new Date());const thisMonth=state.members.filter(m=>monthKey(m.createdAt)===nowM).length;return `<section class="hero"><h1>${state.settings.companyName}</h1><p>MemberHub 會員管理系統｜${today()}</p><div class="grid"><div class="stat"><b>${state.members.length}</b>會員總數</div><div class="stat"><b>${thisMonth}</b>本月新增</div><div class="stat"><b>${nextNo()}</b>下一編號</div></div></section><div class="card"><div class="actions"><button class="actionBtn" onclick="setPage('register')">新會員登記<span>填寫資料及儲存會員</span></button><button class="actionBtn" onclick="setPage('members')">會員管理<span>搜尋、查看及匯出</span></button><button class="actionBtn" onclick="setPage('settings')">設定<span>公司名稱及會員編號</span></button></div></div><div class="card"><div class="between"><h2>最近新增會員</h2><span class="pill">最新 5 位</span></div>${state.members.slice(0,5).map(m=>`<div class="memberCard"><b>${m.memberNumber}</b>｜${escapeHtml(m.name)}<div class="muted">${new Date(m.createdAt).toLocaleString('zh-HK')}</div></div>`).join('')||'<div class="empty">暫未有會員資料</div>'}</div>`}
function register(){const f=state.form||newForm();state.form=f;return `<div class="card"><div class="between"><h2>新會員登記</h2><span class="pill">${f.memberNumber}</span></div><div class="formGrid">${field('姓名','name',f.name,'text',true)}${select('性別','gender',f.gender,['','男','女','其他'])}${field('出生年月日','dateOfBirth',f.dateOfBirth,'date',true)}${field('年齡','age',f.age,'number',false,true)}${field('身份證號碼','hkid',f.hkid,'text',true)}${field('電話號碼','phone',f.phone,'tel',true)}${field('電郵地址','email',f.email,'email')}${field('住址','address',f.address,'text')} ${field('緊急聯絡人姓名','emergencyContactName',f.emergencyContactName,'text')}${field('緊急聯絡人電話','emergencyContactPhone',f.emergencyContactPhone,'tel')}<div class="full checkboxLine"><input type="checkbox" ${f.healthDeclaration?'checked':''} onchange="updateForm('healthDeclaration',this.checked)"><div><b>沒有重大疾病聲明</b><br><span class="muted">本人聲明沒有已知重大疾病，並確認以上資料真確無誤。</span></div></div><div class="field full"><label>備註</label><textarea oninput="updateForm('remarks',this.value)">${escapeHtml(f.remarks)}</textarea></div></div><div class="row" style="margin-top:14px"><button class="ghost" onclick="state.form=newForm();render()">清空表格</button><button class="primary" onclick="submitMember()">確認及儲存</button></div></div>`}
function field(label,key,val,type='text',req=false,readonly=false){return `<div class="field"><label>${label}${req?' *':''}</label><input data-key="${key}" ${readonly?'readonly':''} type="${type}" value="${escapeHtml(val)}" oninput="updateForm('${key}',this.value)"></div>`}
function select(label,key,val,opts){return `<div class="field"><label>${label} *</label><select onchange="updateForm('${key}',this.value)">${opts.map(o=>`<option ${o===val?'selected':''} value="${escapeHtml(o)}">${o||'請選擇'}</option>`).join('')}</select></div>`}
function members(){const list=filteredMembers();return `<div class="card"><div class="between"><h2>會員管理</h2><button class="primary" onclick="setPage('register')">新增會員</button></div><div class="notice">為保障私隱，列表只顯示姓名及會員編號；查看詳情或刪除會員均需要輸入系統密碼。</div><div class="toolbar"><div class="formGrid"><div class="field"><label>月份</label><select onchange="state.month=this.value;render()">${uniqueMonths().map(m=>`<option ${m===state.month?'selected':''}>${m}</option>`).join('')}</select></div><div class="field"><label>快速搜尋</label><input placeholder="姓名 / 會員編號 / 電話 / 身份證" value="${escapeHtml(state.search)}" oninput="state.search=this.value;render()"></div></div></div><div class="memberList">${list.map(memberCard).join('')||'<div class="empty">沒有符合條件的會員</div>'}</div></div>${state.viewMember?memberDetailModal(state.viewMember):''}`}
function memberCard(m){return `<div class="memberCard compact"><div><div class="memberName">${escapeHtml(m.name)||'未命名會員'}</div><div class="muted">會員編號：<b>${escapeHtml(m.memberNumber)}</b></div></div><div class="row"><button class="primary small" onclick="viewMember('${m.id}')">查看</button><button class="danger small" onclick="delMember('${m.id}')">刪除</button></div></div>`}
function memberDetailModal(m){return `<div class="modalBackdrop" onclick="closeView()"><div class="modalCard" onclick="event.stopPropagation()"><div class="between"><div><h2>${escapeHtml(m.name)} 的會員檔案</h2><span class="pill">${escapeHtml(m.memberNumber)}</span></div><button class="ghost" onclick="closeView()">關閉</button></div><div class="infoGrid">${memberRows(m).slice(2).map(([a,b])=>`<div><b>${a}</b><br><span>${escapeHtml(b)}</span></div>`).join('')}</div><div class="row" style="margin-top:16px"><button onclick='exportPDF(${JSON.stringify(m).replace(/'/g,"&#39;")})'>列印 / PDF</button><button onclick='exportWord(${JSON.stringify(m).replace(/'/g,"&#39;")})'>Word</button><button class="danger" onclick="delMember('${m.id}')">刪除會員</button></div></div></div>`}
function updateNextPreview(){const el=document.getElementById('nextPreview'); if(el) el.textContent=nextNo();}
function settings(){const s=state.settings;return `<div class="card"><h2>設定</h2><div class="formGrid"><div class="field"><label>公司名稱</label><input value="${escapeHtml(s.companyName)}" oninput="state.settings.companyName=this.value;save('${LS_SETTINGS}',state.settings)"></div><div class="field"><label>系統密碼</label><input type="password" value="${escapeHtml(s.password)}" oninput="state.settings.password=this.value;save('${LS_SETTINGS}',state.settings)"></div><div class="field"><label>會員編號前綴</label><input value="${escapeHtml(s.memberPrefix)}" oninput="state.settings.memberPrefix=this.value;save('${LS_SETTINGS}',state.settings);updateNextPreview()"></div><div class="field"><label>起始 / 目前流水號</label><input type="number" value="${s.currentSequence||1}" oninput="state.settings.currentSequence=Number(this.value||1);save('${LS_SETTINGS}',state.settings);updateNextPreview()"></div><div class="full checkboxLine"><input type="checkbox" ${s.includeYear?'checked':''} onchange="state.settings.includeYear=this.checked;save('${LS_SETTINGS}',state.settings);render()"><b>會員編號加入年份</b></div><div class="full checkboxLine"><input type="checkbox" ${s.includeMonth?'checked':''} onchange="state.settings.includeMonth=this.checked;save('${LS_SETTINGS}',state.settings);render()"><b>會員編號加入月份</b></div></div><div class="card"><b>下一個會員編號：</b><span id="nextPreview" class="pill">${nextNo()}</span></div><button class="danger" onclick="if(confirm('確定清空所有會員資料？')){state.members=[];save('${LS_MEMBERS}',[]);toast('已清空');render()}">清空所有會員資料</button></div>`}
function nav(){return `<nav class="bottomNav"><button class="${state.page==='home'?'active':''}" onclick="setPage('home')">首頁</button><button class="${state.page==='register'?'active':''}" onclick="setPage('register')">登記</button><button class="${state.page==='members'?'active':''}" onclick="setPage('members')">會員</button><button class="${state.page==='settings'?'active':''}" onclick="setPage('settings')">設定</button></nav>`}
function render(){const pages={home,register,members,settings};document.getElementById('app').innerHTML=`${state.toast?`<div class="toast">${state.toast}</div>`:''}<main class="app">${pages[state.page]()}</main>${nav()}<div id="printArea" class="printOnly"></div>`}
render();
